### ISSUE TITLE
intro.nvim not starting

### ISSUE THREAD

**Issue by daUnknownCoder** [OXY2DEV/intro.nvim#1]
```lua
        ...eutronVim/lazy/lazy.nvim/lua/lazy/manage/task/plugin.lua:84: Vim:E154: Duplicate tag "intro.nvim-colors" in file /home/daUnknownCoder/.local/share/NeutronVim/lazy/intro.nvim/doc//intro-nvim.txt
```

config:
```lua
return {
  "OXY2DEV/intro.nvim",
  config = function()
    local intro_status_ok, intro = pcall(require, "intro")
    if not intro_status_ok then
      print("intro not found!")
    end
    intro.setup({
      preset = "nvim_color_animated",
      animations = { delay = 0, updateDelay = 100 },
      components = {
        type = "time",
      },
    })
  end,
}
```

**Comment by OXY2DEV** [comment]
I removed the duplicate tag in the help file. I can install it via lazy now.

Can you check if the issue is resolved?

On a side note, I am currently working on changes to the plugin. So the help file may be a bit outdated(especially the `presets` section, as I am working on it right now).

**Comment by OXY2DEV** [comment]
```lua
{
  preset = "intro_animated"
}
```
No longer works

Use this instead
```lua
{
  preset = {
    name = "nvim",
    opts = { "animated" }
  }
}
```

**Comment by daUnknownCoder** [comment]
ok the error of lazy is gone but how do i start it?

```lua
return {
  "OXY2DEV/intro.nvim",
  lazy = false,
  event = "VeryLazy",
  config = function()
    local intro_status_ok, intro = pcall(require, "intro")
    if not intro_status_ok then
      print("intro not found!")
    end
    intro.setup({
      preset = {
        name = "nvim_color_animated",
        opts = { "animated" },
      },
      animations = { delay = 0, updateDelay = 100 },
      components = {
        type = "time",
      },
    })
  end,
}
```

**Comment by OXY2DEV** [comment]
You should do it like this

```lua
intro.setup({
  preset = {
    name = "nvim",
    opts = { "animated" }
  }
});
```

In case you are wondering, the start delay and frame delay don't need manual setup anymore. As they are applied by the preset.

Option merging(using a `preset` and normal options at the same time), no longer works. It will be added later.

**Comment by daUnknownCoder** [comment]
bro i meant, how to get the startscreen plugin?

**Comment by OXY2DEV** [comment]
> bro i meant, how to get the startscreen plugin?

I don't think I actually understood what you meant. Your config shows that you are installing the plugin.

Can you elaborate?

**Comment by daUnknownCoder** [comment]
according to my config, the thing should popup on startup, but it takes me to an empty buffer, nothing on startup

**Comment by OXY2DEV** [comment]
> according to my config, the thing should popup on startup, but it takes me to an empty buffer, nothing on startup

Why are you lazy loading the plugin? Remove the `event = "VeryLazy"` part.

There's no point of the plugin if it can't start before other plugins.

Have you tried using this
```lua
return {
  "OXY2DEV/intro.nvim",
  config = function()
    require("intro").setup()
  end
}
```

**Comment by daUnknownCoder** [comment]
no doesnt work, it doesnt open on startup

**Comment by OXY2DEV** [comment]
> no doesnt work, it doesnt open on startup

What happens on Neovim's start?

Does it open the normal Neovim intro page?
![this one](https://github.com/OXY2DEV/intro.nvim/assets/122956967/105cdd41-63b8-4001-948a-62eeb265eeed)

Or does it open a completely empty buffer (with no text)?

If the buffer is completely empty run the following command
```
:lua print(vim.bo.filetype)
```

If the plugin is working it would print `intro` if the plugin is working and won't return anything if it isn't.

**Comment by daUnknownCoder** [comment]
can ya open the issue?

![image](https://github.com/OXY2DEV/intro.nvim/assets/84800625/8c3fd863-44fa-408a-8156-f30ae402878c)
`akinsho/nvim-bufferline`, lualine

**Comment by OXY2DEV** [comment]
> can ya open the issue?
> 
> ![image](https://private-user-images.githubusercontent.com/84800625/323694246-8c3fd863-44fa-408a-8156-f30ae402878c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NTk5MDgsIm5iZiI6MTcxMzQ1OTYwOCwicGF0aCI6Ii84NDgwMDYyNS8zMjM2OTQyNDYtOGMzZmQ4NjMtNDRmYS00MDhhLTgxNTYtZjMwYWU0MDI4NzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE3MDAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZTcyZjYzMzZkMjY0ODMxZjRiYzNjODNhZTNkZDg4NjY1MmRjYzE3NjYxY2I3MTIxYzIwNmJjYzM4NjgxYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wRvMFaxjb3b4qupBnk4OSVRldWrxttCOujloDq6D8lY) `akinsho/nvim-bufferline`, lualine

It shouldn't be saying `new file`. Are you sure the plugin is loading?

Just to make sure the plugin is loading you can check for a command

```
:Gradient "111111" "ffffff" 10
```

See if it throws an error.

**Comment by daUnknownCoder** [comment]
If the buffer is completely empty run the following command

`:lua print(vim.bo.filetype)`

returns nothing,
`:Gradient "111111" "ffffff" 10`
```lua
E492: Not an editor command: Gradient "111111" "ffffff" 10
```

in the lazy menu, i see its not loaded:
```lua
return {
  "OXY2DEV/intro.nvim",
  config = function()
    require("intro").setup()
  end
}
```

with this config:
```lua
return {
  "OXY2DEV/intro.nvim",
  lazy = false,
  config = function()
    local intro_status_ok, intro = pcall(require, "intro")
    if not intro_status_ok then
      print("intro not found!")
    end
    intro.setup({
      preset = {
        name = "nvim_color_animated",
        opts = { "animated" },
      },
      animations = { delay = 0, updateDelay = 100 },
      components = {
        type = "time",
      },
    })
  end,
}
```
i get `:lua vim.print(vim.bo.filetype)` is intro, but it looks like:
![image](https://github.com/OXY2DEV/intro.nvim/assets/84800625/3e586229-b8e1-43d4-b336-b972f55dbd3d)
and the `gradient` command also return something

**Comment by OXY2DEV** [comment]
I am testing with the plugin and have found this bug too.

I will see what I can do to fix it.

**Comment by OXY2DEV** [comment]
I did a fresh installation of the plugin and it seems to work just fine. I thought the plugin was bugged but found nothing.

I checked the code of the plugin and it works like normal. So it can't be from there.

Here's the config I used to test.
```lua
return {
  "OXY2DEV/intro.nvim",
  config = function()
    require("intro").setup()
  end
}
```

I can't seem to recreate the issue. Have you tried checking the message logs? You can check it via the `:messages` command.

Since the buffer is getting correctly named then the plugin is doing what it's supposed to do.

But for some reason `vim.cmd()` isn't doing what it's meant to.


What are you running Neovim on? And what version are you using?

The plugin is meant to work on 0.9.5 as that's what I am using.

**Comment by daUnknownCoder** [comment]
ok i get the plugin by updating:
im using 0.9.5
![image](https://github.com/OXY2DEV/intro.nvim/assets/84800625/e1d1e5c4-e7af-4e57-9f2a-62f4a86f341b)

current config:
```lua
return {
  "OXY2DEV/intro.nvim",
  name = "intro",
  lazy = false,
  config = function()
    local intro_status_ok, intro = pcall(require, "intro")
    if not intro_status_ok then
      print("intro not found!")
    end
    intro.setup({
      preset = {
        name = "nvim",
        opts = { "animated" },
      },
      animations = { delay = 0, updateDelay = 100 },
      components = {
        type = "time",
      },
    })
  end,
}
```

https://github.com/OXY2DEV/intro.nvim/assets/84800625/009aba52-c3af-4e5b-9087-5d45d8e0de0e

but i dont get animation...

**Comment by OXY2DEV** [comment]
You are overly complicating the entire thing.

Just use `intro.setup()`. You are just setting everything up again.

The animation *is* happening. It's just that some other plugin or your terminal is messing with it.

For some odd reason your terminal isn't updating the screen(like it should be doing). You can see that once all the animation is finished it just jumps to the end instead of playing it.


Here's what you can do to diagnose the issue. If you are on `linux` go to `~/.local/share/nvim/lazy/intro.nvim/lua/intro/`. Inside you will see a file named `presets.lua`. Open that file.

The first table(after the function) is named `nvim`. Go to the table and check for a property named `animated`. Inside it there's another property called `animations`.

Inside you will see this
```lua
delay = 15
```

It's in line 129.

Change `15` to something like `500` and open Neovim. Tell me what happens.

**Comment by OXY2DEV** [comment]
> You are overly complicating the entire thing.
> 
> Just use `intro.setup()`. You are just setting everything up again.
> 
> The animation _is_ happening. It's just that some other plugin or your terminal is messing with it.
> 
> For some odd reason your terminal isn't updating the screen(like it should be doing). You can see that once all the animation is finished it just jumps to the end instead of playing it.
> 
> Here's what you can do to diagnose the issue. If you are on `linux` go to `~/.local/share/nvim/lazy/intro.nvim/lua/intro/`. Inside you will see a file named `presets.lua`. Open that file.
> 
> The first table(after the function) is named `nvim`. Go to the table and check for a property named `animated`. Inside it there's another property called `animations`.
> 
> Inside you will see this
> 
> ```lua
> delay = 15
> ```
> 
> It's in line 129.
> 
> Change `15` to something like `500` and open Neovim. Tell me what happens.

[This is the line](https://github.com/OXY2DEV/intro.nvim/blob/c49155884b0a20820899722f41dc42ed9d46c939/lua/intro/presets.lua#L129)

**Comment by OXY2DEV** [comment]
Due to lack of activity, this issue will be closed.
